sudo: required
dist: trusty
language: node_js
node_js:
  - "4"
  - "5"
  - "6"
before_script:
  - ./scripts/start-server.sh
  - node test/app-fixture.js &
script:
  - make ci
after_script:
  - ./scripts/stop-server.sh
  - kill -9 `cat pid.txt`
notifications:
  irc: "irc.freenode.org#brass-monkey"
branches:
  only:
  - master
